### ISSUE TITLE
Feature: Specify authentication to use for git related actions

### ISSUE THREAD

**Issue by graytonio** [graytonio/flagops#17]
Should be able to pass authentication to authenticate the git client.

Supported Methods:
- SSH Private Key
- Basic Auth

Sensitive data should be able to be passed as an environment variable containing the data or a file path.

For example a private key can be specified as either
```yaml
key: $SSH_PRIVATE_KEY

# or

key: ~/.ssh/id_rsa
```
