### ISSUE TITLE
Feature: Allow git as source for templates

### ISSUE THREAD

**Issue by graytonio** [graytonio/flagops#8]
Git can be used as a destination for templates but it should also be able to pull in a git repo to use as a source for templates. Config should be updated to reflect multiple source options like destination.

Example
```
src:
  type: git
  repo: git@github.com:my-repo
  path: apps/nginx
```
